/** Top 5 cities per country (by population) for quick access in city selectors */
const POPULAR_CITIES: Record<string, string[]> = {
  FR: ["Paris", "Marseille", "Lyon", "Toulouse", "Nice"],
  DE: ["Berlin", "Hamburg", "München", "Köln", "Frankfurt"],
  ES: ["Madrid", "Barcelona", "Valencia", "Sevilla", "Zaragoza"],
  IT: ["Roma", "Milano", "Napoli", "Torino", "Palermo"],
  GB: ["London", "Birmingham", "Manchester", "Leeds", "Glasgow"],
  US: ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix"],
  CA: ["Toronto", "Montreal", "Vancouver", "Calgary", "Ottawa"],
  BE: ["Bruxelles", "Anvers", "Gand", "Charleroi", "Liège"],
  CH: ["Zürich", "Genève", "Basel", "Bern", "Lausanne"],
  NL: ["Amsterdam", "Rotterdam", "Den Haag", "Utrecht", "Eindhoven"],
  PT: ["Lisboa", "Porto", "Amadora", "Braga", "Coimbra"],
  AT: ["Wien", "Graz", "Linz", "Salzburg", "Innsbruck"],
  PL: ["Warszawa", "Kraków", "Łódź", "Wrocław", "Poznań"],
  SE: ["Stockholm", "Göteborg", "Malmö", "Uppsala", "Västerås"],
  NO: ["Oslo", "Bergen", "Trondheim", "Stavanger", "Drammen"],
  DK: ["København", "Aarhus", "Odense", "Aalborg", "Esbjerg"],
  FI: ["Helsinki", "Espoo", "Tampere", "Vantaa", "Oulu"],
  IE: ["Dublin", "Cork", "Limerick", "Galway", "Waterford"],
  GR: ["Athènes", "Thessalonique", "Patras", "Héraklion", "Larissa"],
  TR: ["Istanbul", "Ankara", "Izmir", "Bursa", "Antalya"],
  RU: ["Moscou", "Saint-Pétersbourg", "Novossibirsk", "Iekaterinbourg", "Kazan"],
  CN: ["Shanghai", "Beijing", "Guangzhou", "Shenzhen", "Chengdu"],
  JP: ["Tokyo", "Osaka", "Yokohama", "Nagoya", "Sapporo"],
  KR: ["Seoul", "Busan", "Incheon", "Daegu", "Daejeon"],
  IN: ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai"],
  BR: ["São Paulo", "Rio de Janeiro", "Brasília", "Salvador", "Fortaleza"],
  MX: ["Ciudad de México", "Guadalajara", "Monterrey", "Puebla", "Tijuana"],
  AR: ["Buenos Aires", "Córdoba", "Rosario", "Mendoza", "Tucumán"],
  AU: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide"],
  ZA: ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth"],
  MA: ["Casablanca", "Rabat", "Fès", "Marrakech", "Tanger"],
  DZ: ["Alger", "Oran", "Constantine", "Annaba", "Blida"],
  TN: ["Tunis", "Sfax", "Sousse", "Kairouan", "Bizerte"],
  EG: ["Le Caire", "Alexandrie", "Gizeh", "Charm el-Cheikh", "Louxor"],
  SN: ["Dakar", "Thiès", "Saint-Louis", "Kaolack", "Ziguinchor"],
  CI: ["Abidjan", "Bouaké", "Daloa", "Yamoussoukro", "San-Pédro"],
  CM: ["Douala", "Yaoundé", "Garoua", "Bamenda", "Bafoussam"],
  NG: ["Lagos", "Kano", "Ibadan", "Abuja", "Port Harcourt"],
  SA: ["Riyad", "Djeddah", "La Mecque", "Médine", "Dammam"],
  AE: ["Dubaï", "Abou Dabi", "Charjah", "Al Aïn", "Ajman"],
  TH: ["Bangkok", "Chiang Mai", "Pattaya", "Nakhon Ratchasima", "Phuket"],
  VN: ["Hô Chi Minh-Ville", "Hanoï", "Da Nang", "Haiphong", "Can Tho"],
  ID: ["Jakarta", "Surabaya", "Bandung", "Medan", "Semarang"],
  CO: ["Bogota", "Medellín", "Cali", "Barranquilla", "Cartagena"],
  CL: ["Santiago", "Valparaíso", "Concepción", "Antofagasta", "Temuco"],
  RO: ["Bucarest", "Cluj-Napoca", "Timișoara", "Iași", "Constanța"],
  CZ: ["Prague", "Brno", "Ostrava", "Plzeň", "Liberec"],
  HU: ["Budapest", "Debrecen", "Szeged", "Miskolc", "Pécs"],
  HR: ["Zagreb", "Split", "Rijeka", "Osijek", "Zadar"],
  LU: ["Luxembourg", "Esch-sur-Alzette", "Differdange", "Dudelange", "Ettelbruck"],
  SG: ["Singapore"],
  NZ: ["Auckland", "Wellington", "Christchurch", "Hamilton", "Tauranga"],
  MY: ["Kuala Lumpur", "George Town", "Johor Bahru", "Ipoh", "Shah Alam"],
  PH: ["Manille", "Quezon City", "Davao", "Cebu", "Zamboanga"],
  PK: ["Karachi", "Lahore", "Islamabad", "Faisalabad", "Rawalpindi"],
  BD: ["Dhaka", "Chittagong", "Khulna", "Rajshahi", "Sylhet"],
  PE: ["Lima", "Arequipa", "Trujillo", "Chiclayo", "Cusco"],
  CU: ["La Havane", "Santiago de Cuba", "Camagüey", "Holguín", "Santa Clara"],
  IL: ["Tel Aviv", "Jérusalem", "Haïfa", "Rishon LeZion", "Ashdod"],
  LB: ["Beyrouth", "Tripoli", "Sidon", "Tyr", "Jounieh"],
  JO: ["Amman", "Zarqa", "Irbid", "Aqaba", "Salt"],
  KE: ["Nairobi", "Mombasa", "Kisumu", "Nakuru", "Eldoret"],
  GH: ["Accra", "Kumasi", "Tamale", "Sekondi-Takoradi", "Cape Coast"],
  ET: ["Addis-Abeba", "Dire Dawa", "Adama", "Gondar", "Hawassa"],
  TZ: ["Dar es Salaam", "Dodoma", "Mwanza", "Arusha", "Mbeya"],
  CG: ["Brazzaville", "Pointe-Noire", "Dolisie", "Nkayi", "Owando"],
  CD: ["Kinshasa", "Lubumbashi", "Mbuji-Mayi", "Kisangani", "Kananga"],
  MG: ["Antananarivo", "Toamasina", "Antsirabe", "Fianarantsoa", "Mahajanga"],
  ML: ["Bamako", "Sikasso", "Mopti", "Ségou", "Koutiala"],
  NE: ["Niamey", "Zinder", "Maradi", "Tahoua", "Agadez"],
  BF: ["Ouagadougou", "Bobo-Dioulasso", "Koudougou", "Banfora", "Ouahigouya"],
  TG: ["Lomé", "Sokodé", "Kara", "Kpalimé", "Atakpamé"],
  BJ: ["Cotonou", "Porto-Novo", "Parakou", "Abomey-Calavi", "Djougou"],
  GN: ["Conakry", "Nzérékoré", "Kankan", "Kindia", "Labé"],
  GA: ["Libreville", "Port-Gentil", "Franceville", "Oyem", "Moanda"],
  MR: ["Nouakchott", "Nouadhibou", "Kiffa", "Kaédi", "Rosso"],
  TD: ["N'Djamena", "Moundou", "Abéché", "Sarh", "Kélo"],
  LY: ["Tripoli", "Benghazi", "Misrata", "Tarhuna", "Zliten"],
  UA: ["Kyiv", "Kharkiv", "Odessa", "Dnipro", "Lviv"],
  BG: ["Sofia", "Plovdiv", "Varna", "Burgas", "Roussé"],
  RS: ["Belgrade", "Novi Sad", "Niš", "Kragujevac", "Subotica"],
  BA: ["Sarajevo", "Banja Luka", "Tuzla", "Zenica", "Mostar"],
  SK: ["Bratislava", "Košice", "Prešov", "Žilina", "Nitra"],
  SI: ["Ljubljana", "Maribor", "Celje", "Kranj", "Koper"],
  EE: ["Tallinn", "Tartu", "Narva", "Pärnu", "Kohtla-Järve"],
  LV: ["Riga", "Daugavpils", "Liepāja", "Jelgava", "Jūrmala"],
  LT: ["Vilnius", "Kaunas", "Klaipėda", "Šiauliai", "Panevėžys"],
  AL: ["Tirana", "Durrës", "Vlorë", "Elbasan", "Shkodër"],
  MK: ["Skopje", "Bitola", "Kumanovo", "Prilep", "Tetovo"],
  ME: ["Podgorica", "Nikšić", "Herceg Novi", "Budva", "Bar"],
  GE: ["Tbilissi", "Batoumi", "Kutaisi", "Roustavi", "Soukhoumi"],
  AM: ["Erevan", "Gyumri", "Vanadzor", "Vagharshapat", "Hrazdan"],
  AZ: ["Bakou", "Gandja", "Sumqayit", "Mingachevir", "Lankaran"],
  IS: ["Reykjavik", "Kópavogur", "Hafnarfjörður", "Akureyri", "Reykjanesbær"],
  MT: ["La Valette", "Birkirkara", "Mosta", "Qormi", "Sliema"],
  CY: ["Nicosie", "Limassol", "Larnaca", "Paphos", "Famagouste"],
  BY: ["Minsk", "Gomel", "Moguilev", "Vitebsk", "Grodno"],
  MD: ["Chișinău", "Bălți", "Tiraspol", "Bender", "Cahul"],
  BO: ["La Paz", "Santa Cruz", "Cochabamba", "Sucre", "Oruro"],
  CR: ["San José", "Alajuela", "Cartago", "Heredia", "Liberia"],
  DO: ["Saint-Domingue", "Santiago", "La Romana", "San Pedro de Macorís", "Puerto Plata"],
  EC: ["Quito", "Guayaquil", "Cuenca", "Santo Domingo", "Ambato"],
  GT: ["Guatemala", "Mixco", "Villa Nueva", "Quetzaltenango", "Escuintla"],
  HT: ["Port-au-Prince", "Cap-Haïtien", "Gonaïves", "Les Cayes", "Jacmel"],
  HN: ["Tegucigalpa", "San Pedro Sula", "La Ceiba", "Choloma", "Comayagua"],
  JM: ["Kingston", "Montego Bay", "Spanish Town", "Portmore", "May Pen"],
  PA: ["Panama", "Colón", "David", "Santiago", "Chitré"],
  PY: ["Asunción", "Ciudad del Este", "Encarnación", "San Lorenzo", "Luque"],
  UY: ["Montevideo", "Salto", "Paysandú", "Las Piedras", "Rivera"],
  VE: ["Caracas", "Maracaibo", "Valencia", "Barquisimeto", "Maracay"],
  AO: ["Luanda", "Huambo", "Lobito", "Benguela", "Lubango"],
  BW: ["Gaborone", "Francistown", "Molepolole", "Maun", "Serowe"],
  MU: ["Port-Louis", "Beau Bassin-Rose Hill", "Vacoas-Phoenix", "Curepipe", "Quatre Bornes"],
  MZ: ["Maputo", "Matola", "Beira", "Nampula", "Chimoio"],
  NA: ["Windhoek", "Walvis Bay", "Rundu", "Oshakati", "Swakopmund"],
  RW: ["Kigali", "Butare", "Gitarama", "Musanze", "Gisenyi"],
  SD: ["Khartoum", "Omdurman", "Port-Soudan", "Kassala", "El-Obeid"],
  UG: ["Kampala", "Gulu", "Lira", "Mbarara", "Jinja"],
  ZM: ["Lusaka", "Kitwe", "Ndola", "Kabwe", "Livingstone"],
  ZW: ["Harare", "Bulawayo", "Chitungwiza", "Mutare", "Gweru"],
  AF: ["Kaboul", "Kandahar", "Hérat", "Mazar-i-Sharif", "Jalalabad"],
  BH: ["Manama", "Riffa", "Muharraq", "Hamad Town", "Isa Town"],
  KH: ["Phnom Penh", "Siem Reap", "Battambang", "Sihanoukville", "Kampong Cham"],
  KW: ["Koweït", "Hawalli", "Salmiya", "Jahra", "Farwaniya"],
  MN: ["Oulan-Bator", "Erdenet", "Darkhan", "Choibalsan", "Mörön"],
  MM: ["Rangoun", "Mandalay", "Naypyidaw", "Mawlamyine", "Bago"],
  NP: ["Katmandou", "Pokhara", "Patan", "Biratnagar", "Bharatpur"],
  OM: ["Mascate", "Salalah", "Sohar", "Nizwa", "Sur"],
  QA: ["Doha", "Al Wakrah", "Al Khor", "Umm Salal", "Al Rayyan"],
  LK: ["Colombo", "Kandy", "Galle", "Jaffna", "Negombo"],
  TW: ["Taipei", "Kaohsiung", "Taichung", "Tainan", "Hsinchu"],
  UZ: ["Tachkent", "Samarcande", "Boukhara", "Namangan", "Andijan"],
  IQ: ["Bagdad", "Bassora", "Erbil", "Mossoul", "Sulaymaniyah"],
  IR: ["Téhéran", "Mashhad", "Ispahan", "Tabriz", "Chiraz"],
  SY: ["Damas", "Alep", "Homs", "Lattaquié", "Hama"],
  YE: ["Sanaa", "Aden", "Taïz", "Hodeïda", "Ibb"],
};

export function getPopularCities(countryISO: string): string[] {
  return POPULAR_CITIES[countryISO] || [];
}
